Update Deploy.yml

diff --git a/.github/workflows/Deploy.yml b/.github/workflows/Deploy.yml
--- a/.github/workflows/Deploy.yml
+++ b/.github/workflows/Deploy.yml
@@ -38,6 +38,11 @@ on:
           - ""
           - UK_prod_001_crx_p_dfs_l
           - UK_prod_001_chn_p_dfs_l
+      create_release_tag:
+        description: 'Should create a release tag?'
+        required: true
+        type: boolean
+        default: false
 
 env:
   JAVA_VERSION: 21
@@ -53,6 +58,39 @@ jobs:
 
       - name: Send Slack Notification Before Approval
         run: echo "Slack notification sent."
+
+            - name: Validate Inputs
+        run: |
+          if [[ "${{ github.event.inputs.environment_type }}" == "development" ]]; then
+            if [[ -z "${{ github.event.inputs.development_environment }}" ]]; then
+              echo "Error: You must select a development environment."
+              exit 1
+            fi
+            echo "TARGET_ENVIRONMENT=${{ github.event.inputs.development_environment }}" >> $GITHUB_ENV
+          elif [[ "${{ github.event.inputs.environment_type }}" == "sandbox" ]]; then
+            if [[ -z "${{ github.event.inputs.sandbox_environment }}" ]]; then
+              echo "Error: You must select a sandbox environment."
+              exit 1
+            fi
+            echo "TARGET_ENVIRONMENT=${{ github.event.inputs.sandbox_environment }}" >> $GITHUB_ENV
+          elif [[ "${{ github.event.inputs.environment_type }}" == "prod" ]]; then
+            if [[ -z "${{ github.event.inputs.prod_environment }}" ]]; then
+              echo "Error: You must select a prod environment."
+              exit 1
+            fi
+            if [[ "${{ github.ref_type }}" != "tag" ]]; then
+              echo "Error: Production deployments can only be triggered by tags, not branches."
+              exit 1
+            fi
+            if [[ "${{ github.event.inputs.create_release_tag }}" == "true" ]]; then
+            echo "Error: Cannot create a release tag for the 'prod' environment!"
+            exit 1
+            fi
+            echo "TARGET_ENVIRONMENT=${{ github.event.inputs.prod_environment }}" >> $GITHUB_ENV
+          else
+            echo "Error: Invalid environment type."
+            exit 1
+          fi
         
 
       - name: Request Approval
